sudo: required
services:
  - docker
env:
  COMPOSE_VERSION: 1.14.0
before_install:
 - sudo apt-get update
 - sudo apt-get -y -q -o Dpkg::Options::="--force-confnew" install docker-engine
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin
 - AT_MODE=TEST docker-compose up -d
script:
  - docker-compose run app npm test