version: '2'

services:
  mongo:
    restart: always
    image: mongo
#    volumes:
#    - ./data/db:/data/db
#  mongo-express:
#    restart: always
#    image: mongo-express
#    ports:
#      - "8081:8081"
#    depends_on:
#      - mongo
  app:
    build: ./app
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
#    args:
#      TYPE: "test"
#    volumes:
#      - ./data/app/logs:/home/app/.anontown/logs
#      - ./data/app/data:/home/app/.anontown/data
#      - ./data/app/coverage:/home/app/.anontown/coverage