version: '3'

services:
  mongo:
    restart: always
    image: mongo
    volumes:
    - ./data/db:/data/db
  app:
    build: .
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./data/app/logs:/home/app/.anontown/logs
      - ./data/app/data:/home/app/.anontown/data