version: '2'

services:
  mongo:
    restart: always
    image: "mongo:3.0.15"
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    environment:
      SERVER_PORT: "8080"
      DB_URL: "mongodb://mongo:27017/anontown"
      ES_HOST: "es:9200"
    env_file: .env
    ports:
      - "8080:8080"
      - "5858:5858"
    depends_on:
      - mongo
      - es
    volumes:
      - ./:/home/app/.anontown/
  es:
    build: es/.
    restart: always
    env_file: es/.env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536